#!/usr/bin/python
#
# domoticz-mqtt by Theo Arends
#
# Provides Domoticz with MQTT
#
# **** Start of user configuration values

broker = "localhost"       # MQTT broker ip address or name
broker_port = 1883         # MQTT broker port

pub_prefix = "sido"        # Own publish topic or empty string for no publishing
idx_offset = 2000          # Domoticz device id offset

# **** End of user configuration values

import sys
import paho.mqtt.client as mqtt

if len(sys.argv) != 5:
  sys.exit(0)

devidx = sys.argv[1]  # Device id
device = sys.argv[2]  # Werkkamer buro spot
astate = sys.argv[3]  # On / Off
avalue = sys.argv[4]  # On / Off / Set Level: 6 %

if devidx > 0:
  if avalue[:9] == "Set Level":
    part = avalue.split(" ",4)
    payload = part[2]
    mytype = "/DIMMER"
  else:
    payload = astate
    mytype = "/LIGHT"

#  mydevice = str(idx_offset + int(devidx))
  mydevice = device.replace(" ","_")

  mytopic = pub_prefix + "/" + mydevice + mytype
#  print("MQTT  published |"+mytopic+"|"+payload+"|")

  try:
    client = mqtt.Client()
    client.connect(broker, broker_port)
    client.publish(mytopic, payload)
  except:
    pass
